### ISSUE TITLE
How to DONT listen updates.

### ISSUE THREAD

**Issue by AlexSmirnov9107** [nksmnf/nestjs-telegraf#1032]
Is it possible to prevent listening updates from telegram? just use telegram api

**Comment by mtenorio-cmp** [comment]
Use: 
[Ref](https://nestjs-telegraf.vercel.app/extras/bot-injection)
```
 constructor( 
    @InjectBot() private bot: Telegraf<TelegrafContext>,
  ) { }
```

**Comment by evilsprut** [comment]
> Is it possible to prevent listening updates from telegram? just use telegram api

@AlexSmirnov9107 just add `launchOptions: false` in module config.
Ref: https://github.com/evilsprut/nestjs-telegraf/blob/main/lib/utils/create-bot-factory.util.ts#L11C1-L11C1
