### ISSUE TITLE
Cannot install on Nest v10

### ISSUE THREAD

**Issue by zaldih** [nksmnf/nestjs-telegraf#1085]
Nest v10 came out a few days ago but this package only supports version 8 and 9, so npm throws an error when trying to install it.
![image](https://github.com/hypeertech/nestjs-telegraf/assets/16844185/b852e420-aaad-41e4-9a60-ad46ef62f2fd)

_pd: Thanks for this useful package!_

**Comment by frct1** [comment]
Hey
You can use `--force` flag as temporary fix until @hypeertech change peer deps.
https://github.com/hypeertech/nestjs-telegraf/pull/1086
May be this will be merged to fix

**Comment by zaldih** [comment]
Yeah that's what I did. Luckily there doesn't seem to be any problem in this case but better do a more detailed check to ensure compatibility :)

**Comment by evilsprut** [comment]
Fixed in `2.6.4`

**Comment by frct1** [comment]
> Fixed in `2.6.4`

Would be nice to merge https://github.com/hypeertech/nestjs-telegraf/pull/1082 since new nest also running on TypeScript 5.
