### ISSUE TITLE
connect to the same bot from another app

### ISSUE THREAD

**Issue by hillesa** [nksmnf/nestjs-telegraf#1087]
Hello everybody,

I am trying to connect to the same bot from another app context but i receive:
`conflict: terminated by other getupdates request; make sure that only one bot instance is running`

Is it any way to init bot by turning off polling? 

Thank you

**Comment by evilsprut** [comment]
https://github.com/evilsprut/nestjs-telegraf/issues/1032#issuecomment-1647975737
