### ISSUE TITLE
How to get callback_data from context

### ISSUE THREAD

**Issue by Aliph0th** [nksmnf/nestjs-telegraf#1127]
I have a lot of inline buttons that change the language of the bot.  
I want to make **one** function in my `AppUpdate` that would change the language depending on the `callback_data` of the button that was pressed:

```
@Action(['en', 'ru', ...])
   async changeLanguage(@Ctx() ctx: Context) {
      await ctx.deleteMessage();
      ctx.session.language = ??????????????
     ...
   }
```

Buttons:

```
export default Markup.inlineKeyboard([
   [Markup.button.callback('🇬🇧 English', 'en')],
   [Markup.button.callback('🇷🇺 Русский', 'ru')],
  ...
]);

```

**Comment by unnaidan** [comment]
Hello @Aliph0th, how did you solve this?

**Comment by YakovL** [comment]
Yeah, I'd be thankful, too, if you share some code sample
PS Note: related: #1129 

PS Ok, basically this can be solved using console 😄. Like:

    @Action(/confirm_(\d+)_(\d+)_(\d+)/)
    async onPaymentConfirmation(@Ctx() ctx: SceneContext) {
        console.log(ctx)

This showed me that in this case, `ctx.match` is the actual match of a `RegExp` used as the `Action`'s argument. TS doesn't show that correctly, though, so I had to cast `const match = (ctx as ..).match` and then check and destruct `match`
