### ISSUE TITLE
Multiple Dynamic Bot

### ISSUE THREAD

**Issue by saadhossain** [nksmnf/nestjs-telegraf#1148]
I have multiple bot tokens in my database... I would like to fetch them and run multiple bots, one bot for each token..
Is there any solution for this?

**Comment by damir-minkashev** [comment]
@saadhossain Try this [sample/01-complete-app/src/app.module.ts](https://github.com/evilsprut/nestjs-telegraf/blob/main/sample/01-complete-app/src/app.module.ts)
