### ISSUE TITLE
issue with reflect-metadata@0.2.2

### ISSUE THREAD

**Issue by binaryb3ast** [nksmnf/nestjs-telegraf#1177]
ERESOLVE overriding peer dependency
npm WARN While resolving: nestjs-telegraf@2.7.0
npm WARN Found: reflect-metadata@0.2.2
npm WARN node_modules/reflect-metadata
npm WARN   peer reflect-metadata@"^0.1.12 || ^0.2.0" from @nestjs/common@10.3.8
npm WARN   node_modules/@nestjs/common
npm WARN     peer @nestjs/common@"^10.0.0" from @nestjs/core@10.3.8
npm WARN     node_modules/@nestjs/core
npm WARN     5 more (@nestjs/platform-express, @nestjs/testing, ...)
npm WARN   2 more (@nestjs/core, the root project)

**Comment by vad-ii-k** [comment]
Duplicate #1176

**Comment by 0x467** [comment]
Fixed in https://github.com/0x467/nestjs-telegraf/commit/9c0286c23c707f3366f670be3c91d61758186157
