### ISSUE TITLE
Race condition in setting webhook

### ISSUE THREAD

**Issue by mralbertchen** [nksmnf/nestjs-telegraf#1179]
Need an await here: 

https://github.com/bukhalo/nestjs-telegraf/blob/2db96e09257b8aacbdf50a0aa7ae1c56916cb57b/lib/utils/create-bot-factory.util.ts#L12

**Comment by nksmnf** [comment]
Not needed
https://github.com/telegraf/telegraf/issues/1749

> Need an await here:
> 
> https://github.com/bukhalo/nestjs-telegraf/blob/2db96e09257b8aacbdf50a0aa7ae1c56916cb57b/lib/utils/create-bot-factory.util.ts#L12

**Comment by mralbertchen** [comment]
Thanks
