### ISSUE TITLE
documentation website from readme is down

### ISSUE THREAD

**Issue by daggett206** [nksmnf/nestjs-telegraf#1198]
https://nestjs-telegraf.vercel.app/

**Comment by daggett206** [comment]
![image](https://github.com/0x467/nestjs-telegraf/assets/14615740/92bbf97f-1775-4e00-9c65-5eab129a368d)

**Comment by 0x467** [comment]
Fixed in https://github.com/0x467/nestjs-telegraf/pull/1197
