### ISSUE TITLE
Bot should not launch when hosted in Express, Firebase etc.

### ISSUE THREAD

**Issue by toolstik** [nksmnf/nestjs-telegraf#277]
Hello, 

Thank you for that amazing project. It is exactly what I was looking for. But, it looks weird that the plugin launches bot in any case.

https://github.com/bukhalo/nestjs-telegraf/blob/26cc474726737cd1514773c7f30ed5d12995f3fc/lib/utils/create-bot-factory.util.ts#L10

For example, I'm running my bot on the Firebase and I don't need to launch the bot itself since all requests are handled by the Firebase function and from my end, only `bot.handleUpdate()` will be used.

It would be really handy if I could disable launching anyhow. I think the options object is an appropriate place for it.

Thank you

**Comment by evilsprut** [comment]
Hello, @toolstik! That's a great point, I really didn't think about the possibility of working in a serverless environment. It will take me a little time to think through how best to do it. I'll write later. PR's also welcome.
