### ISSUE TITLE
[Bug] Lodash is missed at dependencies

### ISSUE THREAD

**Issue by galkin** [nksmnf/nestjs-telegraf#313]
After `npm install --production` package is broken, because of unresolved lodash.
There are two options for resolving:
1) rewrite [this part](https://github.com/bukhalo/nestjs-telegraf/blob/master/lib/services/base-explorer.service.ts#L3)
2) Add lodash at dependencies

@bukhalo, what do you prefer? Do you need help with this issue?

**Comment by evilsprut** [comment]
Hey, @galkin! Thanks for finding this issue. I think we can add `lodash` as an dependency. I don't need any help for that, but if you send me a PR, I'd be happy to merge it.

**Comment by sachinh19** [comment]
Hey @bukhalo , if @galkin does not work on this, do you mind if I do?
