### ISSUE TITLE
Override error handling

### ISSUE THREAD

**Issue by khadishi** [nksmnf/nestjs-telegraf#352]
hi 
i need to override error handling in create-bot-factory.util.ts , for example:

LINE 8: bot.catch(options.handleError)

**Comment by evilsprut** [comment]
Hey, @khadishi! To catch errors you can use exeption filters. For example, see sample directory of this repository.

**Comment by khadishi** [comment]
Dear, @bukhalo i need to handle bot.launch error, for example:
FetchError: request to https://api.telegram.org/[REDACTED]/getMe failed, reason: connect ECONNREFUSED proxy:8080

**Comment by evilsprut** [comment]
@khadishi you can manually inject `Telegraf` (bot) instance and set `bot.catch` anywhere you want, in some provider, root module or in you entrypoint file.

**Comment by evilsprut** [comment]
@khadishi problem solved?
