### ISSUE TITLE
Getting "context type: telegraf not supported"

### ISSUE THREAD

**Issue by manuelscurti** [nksmnf/nestjs-telegraf#376]
Hello!
I am using Telegraf 4.3.0 and nestjs-telegraf 2.2.2. 
I am creating a bot which uses a custom context, and for doing so I extended Context.
![image](https://user-images.githubusercontent.com/23557705/117335047-9ef13c00-ae92-11eb-872f-69eb0fb8ec2e.png)

To test if everything works I created a sample @ Start command handler as follows:
![image](https://user-images.githubusercontent.com/23557705/117334971-8bde6c00-ae92-11eb-8823-b6daf4e129c5.png)

When sending /start to the bot I can see the answer correctly displayed but in the log of the server I receive the following message:
`
context type: telegraf not supported
`

Am I missing anything in the configuration?

**Comment by evilsprut** [comment]
Hi @manuelscurti, can you create a repository with an error example for I can look at the code?

**Comment by manuelscurti** [comment]
Hi! Thanks for your answer. I was unable to reproduce the error. I think for now we can close this issue.
