### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by evilsprut** [nksmnf/nestjs-telegraf#4]

**Comment by evilsprut** [comment]
Done in https://github.com/bukhalo/nestjs-telegraf/commit/37080937317f492cac9f7bbf57adfa755a648c0c

**Comment by meowlanguages** [comment]
Documentation is too pure

**Comment by galkin** [comment]
> Documentation is too pure

this comment looks not friendly and no actionable. Such comments demotivate open source developers, which contribute to open source for free.

@meowlanguages, could you provide more actionable and friendly communication? For example, https://github.com/bukhalo/nestjs-telegraf/issues/350 is actionable.

**Comment by evilsprut** [comment]
> Documentation is too pure

Yes it is. Unfortunately, I don't have enough time to do everything well. But! This is FOSS, you can always get involved and contribute to make the documentation or code better.

**Comment by bibakid** [comment]
I spent all day trying to understand how connect Scenes. I read all issues and nothing helped, even this didnt help https://habr.com/ru/company/tinkoff/blog/596287/ . They didnt show how to connect Scene outside. Please write some documentation, you did great job but it makes no value when people dont understand how to use it.

**Comment by evilsprut** [comment]
@Gewalt79 If you open the [Telegraf documentation](https://telegraf.js.org), you will understand where this problem comes from. As you understand, the original library has nothing about scenes, router or composer. `nestjs-telegraf` does not do anything on top of the original library, it is just an integration. I think your question belongs in the Telegraf repository. 

In the end, the choice of Telegraf as a basis was not the best in the beginning; poor documentation is a minor problem compared to everything else. But I don't have time to write my own implementation either.
