### ISSUE TITLE
Stable release requirements

### ISSUE THREAD

**Issue by evilsprut** [nksmnf/nestjs-telegraf#40]
- [x] Сover all Telegraf methods with decorators https://github.com/robotmafia-inc/nestjs-telegraf/pull/39
- [x] Upgrade NestJS on v7
- [x] Replace TSLint with ESLint
- [x] Remove unused Travis CI config

**Comment by ghost** [comment]
Released https://github.com/robotmafia-inc/nestjs-telegraf/releases/tag/v1.0.1

**Comment by evilsprut** [comment]
@all-contributors please add @bukhalo for business, code, doc, example, ideas, infra, maintenance, projectManagement, question, review, tutorial
