### ISSUE TITLE
Decorators not chainable

### ISSUE THREAD

**Issue by Satont** [nksmnf/nestjs-telegraf#414]
@Action, @Command decorators not chainable. Will work only one of them.

Steps to reproduce:

Create some method:

```ts
  @Action('CHANNELS')
  @Command('channels')
  start(@Ctx() ctx: Context) {
    return 'Hi!'
  }
  ```
  
 "nestjs-telegraf": "^2.2.3",
  "telegraf": "^4.3.0",

**Comment by felinto-dev** [comment]
I don't think it's a good idea to be able to use multiple decorators at the same time.

In the code you submitted it just returns a "hi", but in a production application where business logic is applied, you would need to respond to the callback query with "ctx.answerCbQuery()", something that cannot be used by commands, for example.

So, you should use NestJS services to store your business logic and use decorators just for the purpose of capturing what data will be used as parameters for the services.

**Comment by xTCry** [comment]
> In the code you submitted it just returns a "hi", but in a production application where business logic is applied, you would need to respond to the callback query with "ctx.answerCbQuery()", something that cannot be used by commands, for example.

For example, you can make a universal handler for the **cancel** event.

```ts
@Command('cancel')
@Action('cancel')
@Action(LocalePhrase.Cancel_Button)
@HearsLocale(KeyboardT.Cancel)
async onСancel(@Context() ctx: IWizardContext) {
    const msg = ctx.i18n.t(LocalePhrase.Canceled);
    if (ctx.updateType === 'callback_query') {
        ctx.tryAnswerCbQuery(msg);
        await ctx.deleteMessage();
    } else {
        await ctx.replyWithHTML(msg);
    }
    ctx.scene.leave();
}
```

In middleware, you can make a custom safe function
```ts
ctx.tryAnswerCbQuery = (...args) => ctx.updateType === 'callback_query' && ctx.answerCbQuery?.(...args);
```

**Comment by felinto-dev** [comment]
I think these various IFs pollute the code a lot.

**Comment by Satont** [comment]
Make sense.

**Comment by evilsprut** [comment]
@Satont, I see @xTCry make some work for that in https://github.com/bukhalo/nestjs-telegraf/pull/469 I need some time for check PR and I will write here if the functionality is implemented and I will add it to the package.

**Comment by evilsprut** [comment]
Done in v2.4.0
