### ISSUE TITLE
Hot get access to ctx.scene in middleware?

### ISSUE THREAD

**Issue by viacheslavsaloid** [nksmnf/nestjs-telegraf#452]
Hello

Scenes functionality works really good. 

But, there is an issue: i can't get ctx.scene inside my middleware before `next()`

<img width="896" alt="Screenshot 2021-07-20 at 15 50 57" src="https://user-images.githubusercontent.com/70704363/126327185-6dee80c3-c80d-420c-89c9-01f87ac82f77.png">

I think, that issue in time, when Scene.Stage of @Scene() is called

**Comment by xTCry** [comment]
Why do I need this piece of code?
If you store the user's session in the _session storage_, then after loading, the state of the scene will automatically load and the user will have the scene again...
