### ISSUE TITLE
No implementation for Inline_keyboard callback_query

### ISSUE THREAD

**Issue by Sedjj** [nksmnf/nestjs-telegraf#5]
```
this.inlineKeyboard(ctx, {
	title: 'message',
	buttons: [
		[{
				text: 'test',
				callback_data: 'test_callback'
			}
		],
	]
})


private static async inlineKeyboard(ctx: Context, msg: any): Promise < void > {
	await ctx.replyWithMarkdown(msg.title, {
		reply_markup: {
			inline_keyboard: msg.buttons,
		},
		parse_mode: 'Markdown'
	});
}


@TelegramActionHandler({
	message: 'test_callback'
})
protected async debugLogs(ctx: Context) {
	console.log('1');
}
```

I tried to use it like that and nothing happened((

**Comment by evilsprut** [comment]
@Sedjj I tried your code and it's working as expected.

I made an example for you of using a module with your code in a [separate repository](https://github.com/bukhalo/nestjs-telegraf-sample). Your code can be found in [bot.service.ts](https://github.com/bukhalo/nestjs-telegraf-sample/blob/master/src/bot/bot.service.ts) the file.

**Comment by Sedjj** [comment]
Thank you for the quick answer to my question, but unfortunately I did not convey the right thought.
If you replace the contents of ```bot.service.ts```
```
import {Injectable} from '@nestjs/common';
import {TelegrafTelegramService, TelegramActionHandler,} from 'nestjs-telegraf';
import {ContextMessageUpdate} from 'telegraf';

@Injectable()
export class BotService {
	constructor(
		private readonly telegrafTelegramService: TelegrafTelegramService,
	) {
	}

	@TelegramActionHandler({onStart: true})
	async start(ctx: ContextMessageUpdate) {
		const me = await this.telegrafTelegramService.getMe();
		console.log(me);
		await ctx.replyWithMarkdown('test', {
			reply_markup: {
				inline_keyboard: [
					[
						{
							text: 'test',
							callback_data: 'test_callback',
						},
					],
				]
			},
			parse_mode: 'Markdown',
		});
	}

	@TelegramActionHandler({message: 'test_callback'})
	protected async debugLogs(ctx: ContextMessageUpdate) {
		console.log('1');
	}
}
```

Then the ```debugLogs``` function will not be called on the ```test_callback``` response.

I'm interested in the ability to build logic for the answer with ```inline_keyboard```.

**Comment by evilsprut** [comment]
@Sedjj Okay, now I get it. I'll release the update in a little while.

**Comment by Sedjj** [comment]
Thank you, this will really save me from a problem that I’ve been tormenting for a long time.

**Comment by evilsprut** [comment]
> Thank you, this will really save me from a problem that I’ve been tormenting for a long time.

It's done. Update the package to [v0.7.0](https://github.com/bukhalo/nestjs-telegraf/releases/tag/v0.7.0) and close the issue if everything works properly. I also updated the repository with an example. https://github.com/bukhalo/nestjs-telegraf-sample/commit/300c268fa33cbb1aabd0be0436161e22dfc2e703

**Comment by Sedjj** [comment]
Yes, it worked! Thanks for the quick decision. I really like your lib and will continue to use it.

**Comment by evilsprut** [comment]
@all-contributors please add @Sedjj for bug, ideas
