### ISSUE TITLE
Cron didn't work 

### ISSUE THREAD

**Issue by Roman-Savka** [nksmnf/nestjs-telegraf#524]
When I try to use cron from @nestjs/schedule   - bot didn't work.
Below you can see my code:

import { Cron } from '@nestjs/schedule';
import { InjectRepository } from '@nestjs/typeorm';
import { On, Update } from 'nestjs-telegraf';
import { Context } from 'telegraf';
import { Repository } from 'typeorm';
import { TelegramBot } from './entities/bot.entity';

@Update()
export class BotService {
  constructor(
    @InjectRepository(TelegramBot)
    private telegramRepo: Repository<TelegramBot>
  ) {}

  @On('message')
  @Cron('*/30 * * * * *')
  async message(ctx: Context): Promise<void> {
    await ctx.reply('Hello there');
  }
}

In terminal I receive:

[Scheduler] TypeError: Cannot read property 'reply' of undefined;

How can I use cron correctly with bot logic (I want receive every 30 seconds message from bot "Hello there"  in chat )?
@bukhalo

**Comment by evilsprut** [comment]
Use something like that

```typescript
export class ScheduledMessages {
  constructor(@InjectBot() bot: Telegraf<Context>) {}

  @Cron('*/30 * * * * *')
  async scheduled_message(): Promise<void> {
      await this.bot.telegram.sendMessage({
        chatId: "",
        text: "",
      });
    }
  }
}
```

**Comment by Roman-Savka** [comment]
> Use something like that
> 
> ```ts
> export class ScheduledMessages {
>   constructor(@InjectBot() bot: Telegraf<Context>) {}
> 
>   @Cron('*/30 * * * * *')
>   async scheduled_message(): Promise<void> {
>       await this.bot.telegram.sendMessage({
>         chatId: "",
>         text: "",
>       });
>     }
>   }
> }
> ```

Thank you for quick reply.

Issue with this code is chatId.

In code below I should put down chat_id manually, but I need to do it automatically( for example: chatId: this.bot.context.chat.id).

If I will use chatId: this.bot.context.chat.id - I will receive TypeError: Cannot read property 'id' of undefined.

Do you have solution of this?

**Comment by evilsprut** [comment]
Where do you want to get the `chat_id` from? Telegraf doesn't know anything about who you want to send the message to.

You can take the `chat_id` from the Telegraf `context`, yes, but it will only be there when you get an update from the Telegram Bot API. For example, a user wrote to the bot, and you can catch that event and take the sender's `chat_id` from context.

This is not a problem with `telegraf` or `nestjs-telegraf` libraries, try to see how the Telegram Bot API works and what data is passed. To better understand how bots work.

**Comment by Roman-Savka** [comment]
Got it.
Thank you
