### ISSUE TITLE
More @Update classes in different modules

### ISSUE THREAD

**Issue by nemcikjan** [nksmnf/nestjs-telegraf#600]
Hi,

I have following setup:

AppModule:
```ts
TelegrafModule.forRootAsync({
            useFactory: (config: ConfigService) => ({
                token: config.get<string>('TELEGRAM_TOKEN'),
                middlewares: [session()],
            }),
            inject: [ConfigService],
        }),
```

AppUpdate:

```ts
@Update()
export class AppUpdate {
....
@On('message')
async onMessage(ctx: Context<Update>) {
...
}
}
```

then I have another module where I have another Update class

```ts
@Update()
export class OtherUpdate {
....
@Command('command')
async onCommand(ctx: Context<Update>) {
...
}
}
```

the issues I'm facing is that whenever I type /command in bot chat, it's caught by @On('message) handler in AppUpdate. When I comment out 'message' handler in AppUpdate, everything is working as expected and 'command' is handled properly. Do you have any suggestion how to avoid this?

**Comment by felinto-dev** [comment]
You can use REGEX to get all text, EXCEPT when starts with "/"

![image](https://user-images.githubusercontent.com/32253743/138856502-a3e8ee9e-b613-4c57-beeb-6e872db899f3.png)

Instead:
`@On('message')
`
You should use:
`@Hears(/^(?!\/).*/)
`
Let me know if it works for you.

**Comment by filipmacek** [comment]
I've also observe this. You only can have one update class

**Comment by ghost** [comment]
@JanNemcik @filipmacek 

I think, it's not a library issue. It's how telegraf works. 

If you register global @Update inside your AppModule then it will firstly catch all incoming messages. 

You can get second parameter inside your `function onMessage (ctx, next) { }` and just call `next()` after the function. In this way, it will call next update. 

But, probably, it's a better way to use different types of handlers. Such as On('text') or Hears('some text')

In this way, there is no reason to handle message in different @Use methods

**Comment by evilsprut** [comment]
This is not a problem with `nestjs-telegraf` or `telegraf`, read the documentation before using the library. If you need to continue executing middlwares, use the `@Next` decorator. Something like that:

```typescript
@Update()
export class AppUpdate {
....
  @On('message')
  async onMessage(@Ctx() ctx: TelegrafContext, @Next(): next: NextFunction) {
    await ctx.reply("A good day not to read the documentation =) ")
    next();
  }
}
```
