### ISSUE TITLE
BUG: only one handler is being called

### ISSUE THREAD

**Issue by aaabramov** [nksmnf/nestjs-telegraf#852]
If you register several handlers (not strictly the same) only the first defined is being called:

_app.update.ts:_
```typescript
import { On, Start, Update } from 'nestjs-telegraf';
import { Context } from 'telegraf';

@Update()
export class MessageHandler {

  @Start()
  async start(ctx: Context) {
    await ctx.reply('start');
  }

  @On('message')
  async handler1(ctx: Context) {
    await ctx.reply('handler 1');
  }

  @On('message')
  async handler2(ctx: Context) {
    await ctx.reply('handler 2');
  }
}
```

---

**Result:**
<img width="836" alt="image" src="https://user-images.githubusercontent.com/11317222/175493093-e54625f5-aa1a-40eb-92cd-6e05584f1357.png">

---

I would expect that all these matching handlers will be called. Is it designed to behave like this? E.g.:
```
usr> /start
bot> start
bot> handler 1
bot> handler 2
```

Is it somehow related to https://github.com/bukhalo/nestjs-telegraf/pull/309 / https://github.com/bukhalo/nestjs-telegraf/pull/310?

**Comment by aaabramov** [comment]
@bukhalo could you please take a look at this one? I can update the docs after getting an answer is needed.

**Comment by evilsprut** [comment]
@aaabramov Hi! It's not a bug, it's a feature) You should check the Telegraf documentation. If one of the handlers is triggered, the other handlers are not processed. To continue execution, you need to call the `next()` function in the middleware. To access the `next` function, use the decorator of the same name.
