### ISSUE TITLE
Using global visibility handlers

### ISSUE THREAD

**Issue by Hambay** [nksmnf/nestjs-telegraf#898]
Hi, I want to use some command and action handlers as global so that they work regardless of the user's current scene.

In my telegraph bot I implemented it like this.

```ts
export const globalCommands = new Composer<AppContext>();
globalCommands.command('start', startHandler);
globalCommands.command('exit', exitHandler);
```

```ts
bot.use((ctx, next) => {
  const scenes: Map<string, BaseScene<AppContext>> = stages.scenes;
  const scene = new SceneContextScene<AppContext, AppWizardSession>(
    ctx,
    scenes,
    stages.options,
  );
  ctx.scene = scene;
  return next();
});

bot.use(globalCommands);

bot.use(globalHandlers);

bot.use(stages.middleware());
```

How do I do this with nestjs-telegraf?

**Comment by Hambay** [comment]
It would be great if we had a GlobalUpdate decorator that would be processed before the scenes

**Comment by Abror4544** [comment]
Any updates on this?

**Comment by YakovL** [comment]
So is there any example of using `Composer` for global handling of `/start`?
How can I do that with higher priority than in-scene `@On('message')` handlers?
