### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by nizyumka** [nksmnf/nestjs-telegraf#990]
### Discussed in https://github.com/hypeertech/nestjs-telegraf/discussions/987

<div type='discussions-op-text'>

<sup>Originally posted by **izumovn** November 12, 2022</sup>
Error handling when telegram unavailable error and application crash when module is initialized?

Example app crashed
![IMAGE 2022-11-12 23:59:32](https://user-images.githubusercontent.com/29820873/201490372-bc823cba-c00d-4bd7-9aab-86c585bb406e.jpg)
</div>

**Comment by EnOane** [comment]
import { ExecutionContext, Injectable, Type } from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { AuthGuard } from '@nestjs/passport';
import { Observable } from 'rxjs';

import {
  IS_PUBLIC_KEY,
  JWT_GUARD,
} from '@/application/api/http-rest/authentication/constants';

@Injectable()
export class HttpJwtAuthGuard extends AuthGuard(JWT_GUARD) {
  public constructor(private readonly reflector: Reflector = new Reflector()) {
    super();
  }

  public canActivate(
    context: ExecutionContext,
  ): boolean | Promise<boolean> | Observable<boolean> {
    const contextType: string = context.getType();

    if (contextType === 'telegraf') {
      return true;
    }

    const isPublic: boolean = this.reflector.getAllAndOverride<boolean>(
      IS_PUBLIC_KEY,
      [context.getHandler(), context.getClass()],
    );

    if (isPublic) {
      return true;
    }

    return super.canActivate(context);
  }
}

**Comment by nizyumka** [comment]
> HttpJwtAuthGuard


It has to work inside the application, and the function is called from another service

**Comment by 0x467** [comment]
Fixed in https://github.com/0x467/nestjs-telegraf/commit/9c0286c23c707f3366f670be3c91d61758186157
